### ISSUE TITLE
Screen readers report a field's help text before any errors

### ISSUE THREAD

**Issue by kbayliss** [torchbox/tbxforms#11]
From @thibaudcolas:

> The fields’ `aria-describedby` has the help text first, error messages second, while in the template we show the error messages first. I think both should match. I like the idea of having errors first, so the beginning of the field’s description is "Error:". Means we don’t need to additionally have `aria-invalid="true"`.

**Comment by thibaudcolas** [comment]
Not strictly required but would be nice to have such a simple fix done from the first release.
