### ISSUE TITLE
Bump django-crispy-forms to 2.0

### ISSUE THREAD

**Issue by jams2** [torchbox/tbxforms#38]
Changelog: https://github.com/django-crispy-forms/django-crispy-forms/blob/main/CHANGELOG.md#20a1-2023-01-18. I don't think the template pack changes affect us, so just review the other items.

Review https://github.com/django-crispy-forms/django-crispy-forms/issues/296 for background on removing the `safe` filter.

Suggest starting from Balazs's branch: https://github.com/torchbox/tbxforms/pull/28

We'll need to push our minimum supported Django version to 3.2 the current LTS release.

---

- [ ] `pyproject.toml` is updated
- [ ] tests are passing

**Comment by jams2** [comment]
Suggest pausing progress on this until https://github.com/torchbox/tbxforms/issues/41 is resolved.

**Comment by kbayliss** [comment]
With #41 now merged, work here can continue :)
