### ISSUE TITLE
Allow tags in non-field errors

### ISSUE THREAD

**Issue by zerolab** [torchbox/tbxforms#65]
We have a use case where we want to provide a validation error with a link to some page. We use `format_html()`

Currently they are stripped out: https://github.com/torchbox/tbxforms/blob/d0ac47ae6121ce1b08eb9ec92d8e64c47d938e0e/tbxforms/templates/tbx/errors.html#L15-L21

**Comment by kbayliss** [comment]
Solved by https://github.com/torchbox/tbxforms/pull/79
